spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DEVCOM?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: meet
    password: meet1234
  mybatis:
    mapper-locations: classpath:/mapper/**/*.xml


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  servlet:
    multipart:
      location: ${user.dir}/yunwoosang/src/main/resources/static/public/img
      max-file-size: 1MB
      max-request-size: 5MB

static:
  path: ${user.dir}/yunwoosang/src/main/resources/static

server:
  port: 1010
mybatis:
  type-aliases-package: com.example.ywstest.dto
  mapper-locations: mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true